name: Print Issues event details
on: [issues]
jobs:
  print-event-details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print event details
        run: echo "${{ toJson(github.event) }}"
